import { NillionBlockCategory, NillionComputeBlock } from './blocks.types';

export const nillionBlockRegistry: NillionComputeBlock[] = [
  {
    id: 'nillion-add',
    name: 'Add',
    category: 'math',
    description: 'Add two numbers together',
    inputs: [
      { name: 'a', type: 'u64', description: 'First number', required: true },
      { name: 'b', type: 'u64', description: 'Second number', required: true },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Sum of a and b' }],
    icon: 'Plus',
    color: '#3B82F6',
    tags: ['basic', 'arithmetic'],
  },
  {
    id: 'nillion-subtract',
    name: 'Subtract',
    category: 'math',
    description: 'Subtract second number from first',
    inputs: [
      { name: 'a', type: 'u64', description: 'Number to subtract from', required: true },
      { name: 'b', type: 'u64', description: 'Number to subtract', required: true },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Difference (a - b)' }],
    icon: 'Minus',
    color: '#3B82F6',
    tags: ['basic', 'arithmetic'],
  },
  {
    id: 'nillion-multiply',
    name: 'Multiply',
    category: 'math',
    description: 'Multiply two numbers',
    inputs: [
      { name: 'a', type: 'u64', description: 'First number', required: true },
      { name: 'b', type: 'u64', description: 'Second number', required: true },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Product of a and b' }],
    icon: 'X',
    color: '#3B82F6',
    tags: ['basic', 'arithmetic'],
  },
  {
    id: 'nillion-divide',
    name: 'Divide',
    category: 'math',
    description: 'Divide first number by second',
    inputs: [
      { name: 'a', type: 'u64', description: 'Dividend', required: true },
      { name: 'b', type: 'u64', description: 'Divisor', required: true },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Quotient (a / b)' }],
    icon: 'Divide',
    color: '#3B82F6',
    tags: ['basic', 'arithmetic'],
  },
  {
    id: 'nillion-modulo',
    name: 'Modulo',
    category: 'math',
    description: 'Get remainder of division',
    inputs: [
      { name: 'a', type: 'u64', description: 'Dividend', required: true },
      { name: 'b', type: 'u64', description: 'Divisor', required: true },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Remainder (a % b)' }],
    icon: 'Percent',
    color: '#3B82F6',
    tags: ['arithmetic'],
  },
  {
    id: 'nillion-power',
    name: 'Power',
    category: 'math',
    description: 'Raise base to exponent',
    inputs: [
      { name: 'base', type: 'u64', description: 'Base number', required: true },
      { name: 'exponent', type: 'u8', description: 'Exponent', required: true, max: 255 },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'base^exponent' }],
    icon: 'Superscript',
    color: '#3B82F6',
    tags: ['arithmetic', 'advanced'],
  },
  {
    id: 'nillion-abs-diff',
    name: 'Absolute Difference',
    category: 'math',
    description: 'Get absolute difference between two numbers',
    inputs: [
      { name: 'a', type: 'u64', description: 'First number', required: true },
      { name: 'b', type: 'u64', description: 'Second number', required: true },
    ],
    outputs: [{ name: 'result', type: 'u64', description: '|a - b|' }],
    icon: 'MoveVertical',
    color: '#3B82F6',
    tags: ['arithmetic'],
  },
  {
    id: 'nillion-greater-than',
    name: 'Greater Than',
    category: 'comparison',
    description: 'Check if first number is greater than second',
    inputs: [
      { name: 'a', type: 'u64', description: 'First number', required: true },
      { name: 'b', type: 'u64', description: 'Second number', required: true },
    ],
    outputs: [{ name: 'result', type: 'u8', description: '1 if a > b, else 0' }],
    icon: 'ChevronRight',
    color: '#10B981',
    tags: ['comparison', 'logic'],
  },
  {
    id: 'nillion-less-than',
    name: 'Less Than',
    category: 'comparison',
    description: 'Check if first number is less than second',
    inputs: [
      { name: 'a', type: 'u64', description: 'First number', required: true },
      { name: 'b', type: 'u64', description: 'Second number', required: true },
    ],
    outputs: [{ name: 'result', type: 'u8', description: '1 if a < b, else 0' }],
    icon: 'ChevronLeft',
    color: '#10B981',
    tags: ['comparison', 'logic'],
  },
  {
    id: 'nillion-equal',
    name: 'Equal',
    category: 'comparison',
    description: 'Check if two numbers are equal',
    inputs: [
      { name: 'a', type: 'u64', description: 'First number', required: true },
      { name: 'b', type: 'u64', description: 'Second number', required: true },
    ],
    outputs: [{ name: 'result', type: 'u8', description: '1 if a == b, else 0' }],
    icon: 'Equal',
    color: '#10B981',
    tags: ['comparison', 'logic'],
  },
  {
    id: 'nillion-greater-equal',
    name: 'Greater Than or Equal',
    category: 'comparison',
    description: 'Check if first number is greater than or equal to second',
    inputs: [
      { name: 'a', type: 'u64', description: 'First number', required: true },
      { name: 'b', type: 'u64', description: 'Second number', required: true },
    ],
    outputs: [{ name: 'result', type: 'u8', description: '1 if a >= b, else 0' }],
    icon: 'ChevronRight',
    color: '#10B981',
    tags: ['comparison', 'logic'],
  },
  {
    id: 'nillion-less-equal',
    name: 'Less Than or Equal',
    category: 'comparison',
    description: 'Check if first number is less than or equal to second',
    inputs: [
      { name: 'a', type: 'u64', description: 'First number', required: true },
      { name: 'b', type: 'u64', description: 'Second number', required: true },
    ],
    outputs: [{ name: 'result', type: 'u8', description: '1 if a <= b, else 0' }],
    icon: 'ChevronLeft',
    color: '#10B981',
    tags: ['comparison', 'logic'],
  },
  {
    id: 'nillion-in-range',
    name: 'In Range',
    category: 'comparison',
    description: 'Check if value is within range [min, max]',
    inputs: [
      { name: 'value', type: 'u64', description: 'Value to check', required: true },
      { name: 'min', type: 'u64', description: 'Minimum value (inclusive)', required: true },
      { name: 'max', type: 'u64', description: 'Maximum value (inclusive)', required: true },
    ],
    outputs: [{ name: 'result', type: 'u8', description: '1 if min <= value <= max, else 0' }],
    icon: 'Scale',
    color: '#10B981',
    tags: ['comparison', 'validation'],
  },
  {
    id: 'nillion-and',
    name: 'AND',
    category: 'logical',
    description: 'Logical AND operation',
    inputs: [
      { name: 'a', type: 'u8', description: 'First boolean (0 or 1)', required: true },
      { name: 'b', type: 'u8', description: 'Second boolean (0 or 1)', required: true },
    ],
    outputs: [{ name: 'result', type: 'u8', description: '1 if both true, else 0' }],
    icon: 'Ampersand',
    color: '#8B5CF6',
    tags: ['logic', 'boolean'],
  },
  {
    id: 'nillion-or',
    name: 'OR',
    category: 'logical',
    description: 'Logical OR operation',
    inputs: [
      { name: 'a', type: 'u8', description: 'First boolean (0 or 1)', required: true },
      { name: 'b', type: 'u8', description: 'Second boolean (0 or 1)', required: true },
    ],
    outputs: [{ name: 'result', type: 'u8', description: '1 if either true, else 0' }],
    icon: 'GitBranch',
    color: '#8B5CF6',
    tags: ['logic', 'boolean'],
  },
  {
    id: 'nillion-not',
    name: 'NOT',
    category: 'logical',
    description: 'Logical NOT operation',
    inputs: [{ name: 'a', type: 'u8', description: 'Boolean value (0 or 1)', required: true }],
    outputs: [{ name: 'result', type: 'u8', description: '1 if false, 0 if true' }],
    icon: 'Ban',
    color: '#8B5CF6',
    tags: ['logic', 'boolean'],
  },
  {
    id: 'nillion-xor',
    name: 'XOR',
    category: 'logical',
    description: 'Logical XOR operation',
    inputs: [
      { name: 'a', type: 'u8', description: 'First boolean (0 or 1)', required: true },
      { name: 'b', type: 'u8', description: 'Second boolean (0 or 1)', required: true },
    ],
    outputs: [{ name: 'result', type: 'u8', description: '1 if exactly one is true, else 0' }],
    icon: 'Shuffle',
    color: '#8B5CF6',
    tags: ['logic', 'boolean'],
  },
  {
    id: 'nillion-if-else',
    name: 'If-Else',
    category: 'control_flow',
    description: 'Conditional selection',
    inputs: [
      { name: 'condition', type: 'u8', description: 'Condition (0 or 1)', required: true },
      { name: 'true_value', type: 'u64', description: 'Value if condition is true', required: true },
      { name: 'false_value', type: 'u64', description: 'Value if condition is false', required: true },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Selected value based on condition' }],
    icon: 'GitBranch',
    color: '#8B5CF6',
    tags: ['control_flow', 'conditional'],
  },
  {
    id: 'nillion-average',
    name: 'Average',
    category: 'statistical',
    description: 'Calculate average of up to 10 numbers',
    inputs: [
      { name: 'values', type: 'array', description: 'Array of values', required: true, arrayLength: 10 },
      { name: 'count', type: 'u8', description: 'Number of valid values (1-10)', required: true, min: 1, max: 10 },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Average value' }],
    icon: 'TrendingUp',
    color: '#F59E0B',
    tags: ['statistics', 'aggregation'],
  },
  {
    id: 'nillion-sum',
    name: 'Sum',
    category: 'statistical',
    description: 'Calculate sum of up to 10 numbers',
    inputs: [
      { name: 'values', type: 'array', description: 'Array of values', required: true, arrayLength: 10 },
      { name: 'count', type: 'u8', description: 'Number of valid values (1-10)', required: true, min: 1, max: 10 },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Sum of all values' }],
    icon: 'Sigma',
    color: '#F59E0B',
    tags: ['statistics', 'aggregation'],
  },
  {
    id: 'nillion-min',
    name: 'Minimum',
    category: 'statistical',
    description: 'Find minimum value in array',
    inputs: [
      { name: 'values', type: 'array', description: 'Array of values', required: true, arrayLength: 10 },
      { name: 'count', type: 'u8', description: 'Number of valid values (1-10)', required: true, min: 1, max: 10 },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Minimum value' }],
    icon: 'ArrowDown',
    color: '#F59E0B',
    tags: ['statistics', 'aggregation'],
  },
  {
    id: 'nillion-max',
    name: 'Maximum',
    category: 'statistical',
    description: 'Find maximum value in array',
    inputs: [
      { name: 'values', type: 'array', description: 'Array of values', required: true, arrayLength: 10 },
      { name: 'count', type: 'u8', description: 'Number of valid values (1-10)', required: true, min: 1, max: 10 },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Maximum value' }],
    icon: 'ArrowUp',
    color: '#F59E0B',
    tags: ['statistics', 'aggregation'],
  },
  {
    id: 'nillion-median',
    name: 'Median',
    category: 'statistical',
    description: 'Calculate median value',
    inputs: [
      { name: 'values', type: 'array', description: 'Array of values', required: true, arrayLength: 10 },
      { name: 'count', type: 'u8', description: 'Number of valid values (1-10)', required: true, min: 1, max: 10 },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Median value' }],
    icon: 'Activity',
    color: '#F59E0B',
    tags: ['statistics', 'aggregation'],
  },
  {
    id: 'nillion-meets-threshold',
    name: 'Threshold Check',
    category: 'use_case',
    description: 'Check if value meets or exceeds threshold',
    inputs: [
      { name: 'value', type: 'u64', description: 'Value to check', required: true },
      { name: 'threshold', type: 'u64', description: 'Threshold value', required: true },
    ],
    outputs: [{ name: 'result', type: 'u8', description: '1 if value >= threshold, else 0' }],
    icon: 'Lock',
    color: '#14B8A6',
    tags: ['access_control', 'validation'],
  },
  {
    id: 'nillion-weighted-average',
    name: 'Weighted Average',
    category: 'use_case',
    description: 'Calculate weighted average of values',
    inputs: [
      { name: 'values', type: 'array', description: 'Array of 5 values', required: true, arrayLength: 5 },
      { name: 'weights', type: 'array', description: 'Array of 5 weights', required: true, arrayLength: 5 },
    ],
    outputs: [{ name: 'result', type: 'u64', description: 'Weighted average' }],
    icon: 'Scale',
    color: '#F59E0B',
    tags: ['statistics', 'ml', 'scoring'],
  },
];

export const getNillionBlock = (id: string): NillionComputeBlock | undefined =>
  nillionBlockRegistry.find((block) => block.id === id);

export const getNillionBlocksByCategory = (category: NillionBlockCategory): NillionComputeBlock[] =>
  nillionBlockRegistry.filter((block) => block.category === category);
